name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]  # Если ветка master, используем ее
  pull_request:
    branches: [ master ]  # Если pull request на master

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep (SAST)
        run: |
          curl -sL https://github.com/returntocorp/semgrep/releases/download/v1.76.0/semgrep-linux-amd64-v1.76.0.tar.gz -o semgrep.tar.gz
          tar -xvf semgrep.tar.gz
          sudo mv semgrep /usr/local/bin/

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"  # Настройка для конфигурации семгрепа

  dast:
    runs-on: ubuntu-latest
    needs: sast  # Этот блок выполнится после SAST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Juice Shop in Docker Container
        run: |
          docker run -d -p 3000:3000 --name juice bkimminich/juice-shop
          # Запускаем Juice Shop в контейнере

      - name: Wait for app to start
        run: sleep 20  # Ждем, чтобы приложение успело запуститься

      - name: Run OWASP ZAP Scan (DAST)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'  # Сканируем Juice Shop
