name: DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  devsecops:
    name: DevSecOps Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Node.js для Juice Shop
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # SAST сканирование с помощью Semgrep
      - name: Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
            p/nodejs
            p/owasp-top-ten
            p/xss
            p/jwt
          
      # Установка зависимостей для Juice Shop
      - name: Install dependencies
        run: npm install

      # Сборка приложения
      - name: Build application
        run: npm run build || echo "Building application..."

      # Запуск приложения в фоновом режиме для DAST
      - name: Start application
        run: |
          npm start &
          sleep 10  # Даем приложению время запуститься
        env:
          NODE_ENV: test

      # DAST сканирование с OWASP ZAP
      - name: OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.github/workflows/zap-rules.tsv'
          cmd_options: '-a'

      # Создаем файл правил для ZAP (чтобы уменьшить ложные срабатывания)
      - name: Create ZAP rules file
        run: |
          mkdir -p .github/workflows
          cat << 'EOF' > .github/workflows/zap-rules.tsv
          10016	IGNORE	(Modern Web Application)
          10027	IGNORE	(Information Disclosure - Suspicious Comments)
          10049	IGNORE	(Non-Storable Content)
          10054	IGNORE	(Cookie Without SameSite Attribute)
          10055	IGNORE	(CSP Scanner)
          10063	IGNORE	(Permissions Policy Header Not Set)
          EOF

      # Проверка зависимостей
      - name: Dependency Check
        run: npm audit --json > npm-audit-results.json || true

      # Сохранение результатов сканирования
      - name: Archive scan results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: security-scan-results
          path: |
            semgrep-results.sarif
            npm-audit-results.json
            report.html
