name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sast:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep without failing the job
      run: |
        semgrep --config=p/owasp-top-ten --json --output=semgrep.json || true
        echo "Semgrep scan completed, results saved in semgrep.json"

    - name: Upload Semgrep results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep.json

   dast:
    name: Dynamic Application Security Testing (DAST)
    needs: sast
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    
    steps:
    - uses: actions/checkout@v4
    - name: Wait for Juice Shop to be ready
      run: |
        echo "Waiting for Juice Shop on http://localhost:3000 ..."
        for i in {1..12}; do
          if curl -s http://localhost:3000 >/dev/null; then
            echo "Juice Shop is up!"
            break
          fi
          echo "Waiting..."
          sleep 5
        done
    - name: Check Juice Shop logs
      run: docker logs $(docker ps -q --filter "ancestor=bkimminich/juice-shop")
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: false
        cmd_options: '-a -j'
        github_token: "" # Устанавливаем пустой токен, чтобы отключить создание issues
        issue_title: "" # Отключаем создание issues
      continue-on-error: true 
    - name: Upload ZAP results
      uses: actions/upload-artifact@v4
      with:
        name: zap-results
        path: |
          report_json.json
          report_html.html
          report_md.md
    - name: Display summary
      run: |
        echo "DAST Scan completed"
        if [ -f report_json.json ]; then
          echo "Scan completed successfully"
        fi
