name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sast:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep without failing the job
      run: |
        semgrep --config=p/owasp-top-ten --json --output=semgrep.json || true
        echo "Semgrep scan completed, results saved in semgrep.json"

    - name: Upload Semgrep results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep.json

  dast:
    name: Dynamic Application Security Testing (DAST)
    needs: sast
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
    - uses: actions/checkout@v4

    - name: Wait for Juice Shop to be ready
      run: |
        timeout 60 bash -c 'while ! curl -s http://juice-shop:3000 >/dev/null; do sleep 5; done'

    - name: Run OWASP ZAP Baseline Scan (ignore failures)
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://juice-shop:3000'
        rules_file_name: 'juice-shop-rules.tsv'
        cmd_options: '-a'
      continue-on-error: true

    - name: Upload ZAP results
      uses: actions/upload-artifact@v4
      with:
        name: zap-results
        path: zap-results.json

    - name: Display summary
      run: |
        echo "DAST Scan completed"
        if [ -f zap-results.json ]; then
          echo "Found $(jq '.site[0].alerts | length' zap-results.json) vulnerabilities"
        fi
